<a href="https://colab.research.google.com/github/Moriarty7819/Gold-price-prediction/blob/main/Gold_Price.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_percentage_error
import tensorflow as tf
from keras import Model
from keras.layers import Input, Dense, Dropout
from keras.layers import LSTM

In [3]:
df = pd.read_csv('/content/Gold Futures Historical Data.csv')

In [4]:
df["Date"] = df["Date"].astype(str).str.replace("-", "/")
df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
df["Date"] = df["Date"].dt.strftime("%m/%d/%Y")

In [5]:
df

            Date     Price      Open      High       Low    Vol.  Change %
0     01/03/2005     429.7     438.9     438.9     427.8   82850     -1.98
1     01/04/2005     429.2     430.4     431.3     424.8   54830     -0.12
2     01/05/2005     427.3       429     429.3     425.9   43720     -0.44
3     01/06/2005     421.6       427     428.3     421.1   65180     -1.33
4     01/07/2005     419.5     422.1     425.8     417.2   97970     -0.50
...          ...       ...       ...       ...       ...     ...       ...
4992  02/18/2026  5,009.50  4,898.50  5,031.90  4,868.50   98200      2.11
4993  02/19/2026  4,997.40  4,993.70  5,042.80  4,971.50   87030     -0.24
4994  02/20/2026  5,080.90  5,015.00  5,131.00  4,999.30  136740      1.67
4995  02/23/2026  5,207.50  5,114.00  5,236.70  5,103.20    1620      2.49
4996  02/24/2026  5,157.80  5,243.40  5,250.00  5,091.80    1510     -0.95

[4997 rows x 7 columns]

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4997 entries, 0 to 4996
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      4997 non-null   object
 1   Price     4997 non-null   object
 2   Open      4997 non-null   object
 3   High      4997 non-null   object
 4   Low       4997 non-null   object
 5   Vol.      4997 non-null   int64
 6   Change %  4997 non-null   float64
dtypes: float64(1), int64(1), object(5)
memory usage: 273.4+ KB

In [7]:
df.drop(['Vol.', 'Change %'], axis=1, inplace=True)

In [8]:
NumCols = df.columns.drop(['Date'])
df[NumCols] = df[NumCols].replace({',': ''}, regex=True)
df[NumCols] = df[NumCols].astype('float64')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4997 entries, 0 to 4996
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    4997 non-null   object
 1   Price   4997 non-null   float64
 2   Open    4997 non-null   float64
 3   High    4997 non-null   float64
 4   Low     4997 non-null   float64
dtypes: float64(4), object(1)
memory usage: 195.3+ KB

In [10]:
df['Date'] = pd.to_datetime(df['Date'])
df.sort_values(by='Date', ascending=True, inplace=True)
df.reset_index(drop=True, inplace=True)

In [11]:
df

           Date   Price    Open    High     Low
0    2005-01-03   429.7   438.9   438.9   427.8
1    2005-01-04   429.2   430.4   431.3   424.8
2    2005-01-05   427.3   429.0   429.3   425.9
3    2005-01-06   421.6   427.0   428.3   421.1
4    2005-01-07   419.5   422.1   425.8   417.2
...         ...     ...     ...     ...     ...
4992 2026-02-18  5009.5  4898.5  5031.9  4868.5
4993 2026-02-19  4997.4  4993.7  5042.8  4971.5
4994 2026-02-20  5080.9  5015.0  5131.0  4999.3
4995 2026-02-23  5207.5  5114.0  5236.7  5103.2
4996 2026-02-24  5157.8  5243.4  5250.0  5091.8

[4997 rows x 5 columns]

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4997 entries, 0 to 4996
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    4997 non-null   datetime64[ns]
 1   Price   4997 non-null   float64
 2   Open    4997 non-null   float64
 3   High    4997 non-null   float64
 4   Low     4997 non-null   float64
dtypes: datetime64[ns](1), float64(4)
memory usage: 195.3 KB

In [13]:
df

           Date   Price    Open    High     Low
0    2005-01-03   429.7   438.9   438.9   427.8
1    2005-01-04   429.2   430.4   431.3   424.8
2    2005-01-05   427.3   429.0   429.3   425.9
3    2005-01-06   421.6   427.0   428.3   421.1
4    2005-01-07   419.5   422.1   425.8   417.2
...         ...     ...     ...     ...     ...
4992 2026-02-18  5009.5  4898.5  5031.9  4868.5
4993 2026-02-19  4997.4  4993.7  5042.8  4971.5
4994 2026-02-20  5080.9  5015.0  5131.0  4999.3
4995 2026-02-23  5207.5  5114.0  5236.7  5103.2
4996 2026-02-24  5157.8  5243.4  5250.0  5091.8

[4997 rows x 5 columns]

In [14]:
df.duplicated().sum()

np.int64(0)

In [15]:
df.isnull().sum().sum()

np.int64(0)

In [16]:
test_size = df[df.Date.dt.year.isin([2020,2021,2022,2023,2024, 2025])].shape[0]
test_size

1322

In [17]:
scaler = MinMaxScaler()
scaler.fit(df.Price.values.reshape(-1,1))

MinMaxScaler()

In [18]:
window_size = 60

In [19]:
train_data = df.Price[:-test_size]
train_data = scaler.transform(train_data.values.reshape(-1,1))

In [20]:
X_train = []
y_train = []

for i in range(window_size, len(train_data)):
    X_train.append(train_data[i-60:i, 0])
    y_train.append(train_data[i, 0])

In [21]:
test_data = df.Price[-test_size-60:]
test_data = scaler.transform(test_data.values.reshape(-1,1))

In [22]:
X_test = []
y_test = []

for i in range(window_size, len(test_data)):
    X_test.append(test_data[i-60:i, 0])
    y_test.append(test_data[i, 0])

In [23]:
X_train = np.array(X_train)
X_test  = np.array(X_test)
y_train = np.array(y_train)
y_test  = np.array(y_test)

X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1], 1))
X_test  = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
y_train = np.reshape(y_train, (-1,1))
y_test  = np.reshape(y_test, (-1,1))

In [24]:
print('X_train Shape: ', X_train.shape)
print('y_train Shape: ', y_train.shape)
print('X_test Shape:  ', X_test.shape)
print('y_test Shape:  ', y_test.shape)

X_train Shape:  (3615, 60, 1)
y_train Shape:  (3615, 1)
X_test Shape:   (1322, 60, 1)
y_test Shape:   (1322, 1)

In [25]:
from tensorflow.keras.callbacks import EarlyStopping

In [26]:
early_stop = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

In [27]:
def define_model2():
    input1 = Input(shape=(window_size,1))
    x = LSTM(units = 64, return_sequences=True)(input1)
    x = Dropout(0.2)(x)
    x = LSTM(units = 64, return_sequences=True)(x)
    x = Dropout(0.2)(x)
    x = LSTM(units = 64)(x)
    x = Dropout(0.2)(x)
    x = Dense(32, activation='softmax')(x)
    dnn_output = Dense(1)(x)

    model = Model(inputs=input1, outputs=[dnn_output])
    model.compile(loss='mean_squared_error', optimizer='Nadam')
    model.summary()

    return model

In [28]:
def define_model():
    input1 = Input(shape=(window_size,1))
    x = LSTM(units = 64, return_sequences=True)(input1)
    x = Dropout(0.2)(x)
    x = LSTM(units = 64, return_sequences=True)(x)
    x = Dropout(0.2)(x)
    x = LSTM(units = 64)(x)
    x = Dropout(0.2)(x)
    x = Dense(32, activation='relu')(x)
    dnn_output = Dense(1)(x)

    model = Model(inputs=input1, outputs=[dnn_output])
    model.compile(loss='mean_squared_error', optimizer='Nadam')
    model.summary()

    return model

In [29]:
model = define_model()
history = model.fit(X_train, y_train, epochs=150, batch_size=32, validation_split=0.1, verbose=1)

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 60, 1)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ (None, 60, 64)         │        16,896 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 60, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 60, 64)         │        33,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 60, 64)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_2 (LSTM)                   │ (None, 64)             │        33,024 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 85,057 (332.25 KB)

 Trainable params: 85,057 (332.25 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 17s 102ms/step - loss: 0.0011 - val_loss: 3.0153e-04
Epoch 2/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 20s 97ms/step - loss: 1.9746e-04 - val_loss: 7.5299e-05
Epoch 3/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 97ms/step - loss: 1.5374e-04 - val_loss: 6.8966e-05
Epoch 4/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 101ms/step - loss: 1.2910e-04 - val_loss: 5.4964e-05
Epoch 5/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 20s 100ms/step - loss: 1.1565e-04 - val_loss: 4.1999e-05
Epoch 6/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - loss: 1.0499e-04 - val_loss: 3.5209e-05
Epoch 7/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 96ms/step - loss: 9.6482e-05 - val_loss: 1.0992e-04
Epoch 8/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 87ms/step - loss: 8.2319e-05 - val_loss: 3.0921e-05
Epoch 9/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 96ms/step - loss: 8.6134e-05 - val_loss: 4.6596e-05
Epoch 10/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - loss: 7.6542e-05 - val_loss: 4.4252e-05
Epoch 11/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 99ms/step - loss: 7.8573e-05 - val_loss: 3.1069e-05
Epoch 12/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 92ms/step - loss: 6.8857e-05 - val_loss: 3.1240e-05
Epoch 13/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 91ms/step - loss: 7.1583e-05 - val_loss: 4.0355e-05
Epoch 14/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 97ms/step - loss: 6.7355e-05 - val_loss: 2.8826e-05
Epoch 15/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 99ms/step - loss: 6.8860e-05 - val_loss: 2.1591e-05
Epoch 16/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 96ms/step - loss: 6.4513e-05 - val_loss: 2.3286e-05
Epoch 17/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 88ms/step - loss: 6.4727e-05 - val_loss: 4.9288e-05
Epoch 18/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 96ms/step - loss: 6.4053e-05 - val_loss: 6.0258e-05
Epoch 19/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 97ms/step - loss: 5.8939e-05 - val_loss: 1.7598e-05
Epoch 20/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 97ms/step - loss: 6.1988e-05 - val_loss: 1.8887e-05
Epoch 21/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 85ms/step - loss: 6.4814e-05 - val_loss: 1.8732e-05
Epoch 22/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 92ms/step - loss: 5.9597e-05 - val_loss: 2.0249e-05
Epoch 23/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - loss: 5.8862e-05 - val_loss: 2.1862e-05
Epoch 24/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 97ms/step - loss: 5.2901e-05 - val_loss: 2.7532e-05
Epoch 25/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 95ms/step - loss: 5.0046e-05 - val_loss: 1.5307e-05
Epoch 26/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 90ms/step - loss: 5.3643e-05 - val_loss: 1.7829e-05
Epoch 27/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 98ms/step - loss: 5.6429e-05 - val_loss: 9.2265e-05
Epoch 28/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 96ms/step - loss: 5.3771e-05 - val_loss: 4.0298e-05
Epoch 29/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 101ms/step - loss: 5.0118e-05 - val_loss: 2.8016e-05
Epoch 30/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 85ms/step - loss: 5.1785e-05 - val_loss: 1.8483e-05
Epoch 31/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 93ms/step - loss: 4.6868e-05 - val_loss: 1.6332e-05
Epoch 32/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - loss: 5.0392e-05 - val_loss: 1.2441e-05
Epoch 33/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 17s 165ms/step - loss: 4.9112e-05 - val_loss: 2.6851e-05
Epoch 34/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 13s 91ms/step - loss: 4.8795e-05 - val_loss: 1.6999e-05
Epoch 35/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 99ms/step - loss: 5.2511e-05 - val_loss: 1.0003e-04
Epoch 36/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 99ms/step - loss: 4.8129e-05 - val_loss: 1.4155e-05
Epoch 37/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - loss: 4.7806e-05 - val_loss: 1.0830e-05
Epoch 38/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 87ms/step - loss: 4.6287e-05 - val_loss: 1.9612e-05
Epoch 39/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 91ms/step - loss: 4.5647e-05 - val_loss: 1.3478e-05
Epoch 40/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 101ms/step - loss: 4.6617e-05 - val_loss: 1.2862e-05
Epoch 41/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - loss: 4.6562e-05 - val_loss: 1.0869e-05
Epoch 42/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 94ms/step - loss: 4.8213e-05 - val_loss: 1.3373e-05
Epoch 43/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 100ms/step - loss: 4.5172e-05 - val_loss: 3.4134e-05
Epoch 44/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 97ms/step - loss: 4.6063e-05 - val_loss: 3.4617e-05
Epoch 45/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 102ms/step - loss: 4.4304e-05 - val_loss: 1.0114e-05
Epoch 46/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 101ms/step - loss: 4.4305e-05 - val_loss: 1.2266e-05
Epoch 47/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 19s 90ms/step - loss: 4.2375e-05 - val_loss: 2.1497e-05
Epoch 48/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 97ms/step - loss: 4.5516e-05 - val_loss: 2.2530e-05
Epoch 49/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - loss: 4.2972e-05 - val_loss: 2.4639e-05
Epoch 50/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 99ms/step - loss: 4.3584e-05 - val_loss: 1.0812e-05
Epoch 51/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 87ms/step - loss: 4.6447e-05 - val_loss: 8.7520e-05
Epoch 52/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 90ms/step - loss: 4.0556e-05 - val_loss: 8.6732e-06
Epoch 53/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - loss: 4.1931e-05 - val_loss: 2.6731e-05
Epoch 54/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - loss: 4.0964e-05 - val_loss: 1.9126e-05
Epoch 55/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 91ms/step - loss: 4.1383e-05 - val_loss: 1.1687e-05
Epoch 56/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 88ms/step - loss: 3.8755e-05 - val_loss: 2.4113e-05
Epoch 57/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 97ms/step - loss: 3.9330e-05 - val_loss: 1.3498e-05
Epoch 58/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 97ms/step - loss: 4.0140e-05 - val_loss: 1.4958e-05
Epoch 59/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - loss: 4.3868e-05 - val_loss: 2.8444e-05
Epoch 60/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 90ms/step - loss: 4.1362e-05 - val_loss: 1.9204e-05
Epoch 61/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 95ms/step - loss: 3.9021e-05 - val_loss: 1.2359e-05
Epoch 62/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 97ms/step - loss: 4.0510e-05 - val_loss: 8.3479e-06
Epoch 63/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 99ms/step - loss: 3.8081e-05 - val_loss: 1.1614e-05
Epoch 64/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 90ms/step - loss: 3.9822e-05 - val_loss: 2.3399e-05
Epoch 65/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 88ms/step - loss: 3.9249e-05 - val_loss: 8.1108e-06
Epoch 66/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 97ms/step - loss: 3.8460e-05 - val_loss: 1.4637e-05
Epoch 67/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - loss: 3.9078e-05 - val_loss: 2.0414e-05
Epoch 68/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 97ms/step - loss: 3.7495e-05 - val_loss: 8.5518e-06
Epoch 69/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 91ms/step - loss: 4.0496e-05 - val_loss: 2.2950e-05
Epoch 70/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 99ms/step - loss: 3.6366e-05 - val_loss: 7.6469e-06
Epoch 71/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - loss: 3.6572e-05 - val_loss: 6.4766e-06
Epoch 72/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - loss: 3.8474e-05 - val_loss: 2.4740e-05
Epoch 73/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 87ms/step - loss: 3.8986e-05 - val_loss: 1.9038e-05
Epoch 74/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 93ms/step - loss: 3.7551e-05 - val_loss: 1.2930e-05
Epoch 75/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 101ms/step - loss: 3.6439e-05 - val_loss: 7.9565e-06
Epoch 76/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 99ms/step - loss: 3.7236e-05 - val_loss: 1.0374e-05
Epoch 77/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 93ms/step - loss: 3.6024e-05 - val_loss: 3.4196e-05
Epoch 78/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 90ms/step - loss: 3.6000e-05 - val_loss: 8.1065e-06
Epoch 79/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 100ms/step - loss: 3.7187e-05 - val_loss: 3.4295e-05
Epoch 80/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 103ms/step - loss: 3.7032e-05 - val_loss: 3.0983e-05
Epoch 81/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 20s 97ms/step - loss: 3.7692e-05 - val_loss: 6.6919e-06
Epoch 82/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 99ms/step - loss: 3.4987e-05 - val_loss: 1.2295e-05
Epoch 83/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 103ms/step - loss: 3.7208e-05 - val_loss: 6.7992e-06
Epoch 84/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 101ms/step - loss: 3.6807e-05 - val_loss: 7.5081e-06
Epoch 85/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 20s 92ms/step - loss: 3.5044e-05 - val_loss: 2.8324e-05
Epoch 86/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 92ms/step - loss: 3.7825e-05 - val_loss: 1.8429e-05
Epoch 87/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 101ms/step - loss: 3.6815e-05 - val_loss: 5.8761e-06
Epoch 88/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 100ms/step - loss: 3.4764e-05 - val_loss: 6.8137e-06
Epoch 89/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 100ms/step - loss: 3.4567e-05 - val_loss: 1.5893e-05
Epoch 90/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 89ms/step - loss: 3.5585e-05 - val_loss: 1.3334e-05
Epoch 91/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 100ms/step - loss: 3.8134e-05 - val_loss: 5.9916e-06
Epoch 92/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 20s 100ms/step - loss: 3.4531e-05 - val_loss: 6.4084e-06
Epoch 93/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 99ms/step - loss: 3.4794e-05 - val_loss: 1.1270e-05
Epoch 94/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 87ms/step - loss: 3.5326e-05 - val_loss: 7.2108e-06
Epoch 95/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 96ms/step - loss: 3.5103e-05 - val_loss: 7.3109e-06
Epoch 96/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 101ms/step - loss: 3.4481e-05 - val_loss: 1.5521e-05
Epoch 97/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 100ms/step - loss: 3.4449e-05 - val_loss: 5.9880e-06
Epoch 98/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 99ms/step - loss: 3.2998e-05 - val_loss: 6.0003e-06
Epoch 99/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 88ms/step - loss: 3.6231e-05 - val_loss: 5.9228e-06
Epoch 100/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 99ms/step - loss: 3.3759e-05 - val_loss: 1.1811e-05
Epoch 101/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 103ms/step - loss: 3.3176e-05 - val_loss: 1.1866e-05
Epoch 102/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 20s 96ms/step - loss: 3.1282e-05 - val_loss: 5.6169e-06
Epoch 103/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 94ms/step - loss: 3.2104e-05 - val_loss: 5.4295e-06
Epoch 104/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 102ms/step - loss: 3.3169e-05 - val_loss: 6.3249e-06
Epoch 105/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 100ms/step - loss: 3.1294e-05 - val_loss: 4.0755e-05
Epoch 106/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - loss: 3.3008e-05 - val_loss: 2.2616e-05
Epoch 107/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 91ms/step - loss: 3.1530e-05 - val_loss: 7.2047e-06
Epoch 108/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 103ms/step - loss: 3.2691e-05 - val_loss: 7.0187e-06
Epoch 109/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 101ms/step - loss: 3.0450e-05 - val_loss: 5.8122e-06
Epoch 110/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 99ms/step - loss: 3.1934e-05 - val_loss: 1.1535e-05
Epoch 111/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 92ms/step - loss: 3.0569e-05 - val_loss: 1.2320e-05
Epoch 112/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 93ms/step - loss: 3.0650e-05 - val_loss: 6.2133e-06
Epoch 113/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 99ms/step - loss: 3.1355e-05 - val_loss: 7.2172e-06
Epoch 114/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 99ms/step - loss: 3.4066e-05 - val_loss: 6.7189e-06
Epoch 115/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 101ms/step - loss: 3.1750e-05 - val_loss: 9.0820e-06
Epoch 116/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 89ms/step - loss: 3.0511e-05 - val_loss: 6.2083e-06
Epoch 117/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 99ms/step - loss: 3.0210e-05 - val_loss: 5.2751e-05
Epoch 118/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 101ms/step - loss: 3.0031e-05 - val_loss: 1.3224e-05
Epoch 119/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - loss: 2.8191e-05 - val_loss: 7.4451e-06
Epoch 120/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 88ms/step - loss: 3.0929e-05 - val_loss: 5.3594e-06
Epoch 121/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 95ms/step - loss: 3.0477e-05 - val_loss: 5.2206e-06
Epoch 122/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 99ms/step - loss: 2.9973e-05 - val_loss: 1.7848e-05
Epoch 123/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 102ms/step - loss: 3.0316e-05 - val_loss: 6.5672e-06
Epoch 124/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 19s 89ms/step - loss: 3.0524e-05 - val_loss: 9.8582e-06
Epoch 125/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 101ms/step - loss: 2.9941e-05 - val_loss: 7.9608e-06
Epoch 126/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 101ms/step - loss: 2.8487e-05 - val_loss: 8.4585e-06
Epoch 127/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 100ms/step - loss: 2.8754e-05 - val_loss: 5.5603e-06
Epoch 128/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 95ms/step - loss: 3.0486e-05 - val_loss: 7.4292e-06
Epoch 129/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 93ms/step - loss: 3.0005e-05 - val_loss: 1.0408e-05
Epoch 130/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - loss: 2.8583e-05 - val_loss: 5.9778e-06
Epoch 131/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 99ms/step - loss: 2.9501e-05 - val_loss: 3.0560e-05
Epoch 132/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 97ms/step - loss: 2.8752e-05 - val_loss: 2.5858e-05
Epoch 133/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 91ms/step - loss: 2.8406e-05 - val_loss: 8.7729e-06
Epoch 134/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 99ms/step - loss: 2.6360e-05 - val_loss: 6.0291e-06
Epoch 135/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 101ms/step - loss: 2.6842e-05 - val_loss: 7.0553e-06
Epoch 136/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 100ms/step - loss: 2.6960e-05 - val_loss: 5.2622e-06
Epoch 137/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 89ms/step - loss: 2.7938e-05 - val_loss: 6.4232e-06
Epoch 138/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 93ms/step - loss: 2.7937e-05 - val_loss: 5.2151e-06
Epoch 139/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - loss: 2.6389e-05 - val_loss: 1.0888e-05
Epoch 140/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 100ms/step - loss: 2.8678e-05 - val_loss: 3.2949e-05
Epoch 141/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 96ms/step - loss: 2.5504e-05 - val_loss: 9.1718e-06
Epoch 142/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 91ms/step - loss: 2.8830e-05 - val_loss: 9.0508e-06
Epoch 143/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 100ms/step - loss: 2.8090e-05 - val_loss: 6.4434e-06
Epoch 144/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 98ms/step - loss: 2.5310e-05 - val_loss: 2.8216e-05
Epoch 145/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 99ms/step - loss: 2.8165e-05 - val_loss: 5.0497e-06
Epoch 146/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 9s 88ms/step - loss: 2.7095e-05 - val_loss: 1.2493e-05
Epoch 147/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 11s 96ms/step - loss: 2.7272e-05 - val_loss: 7.3966e-06
Epoch 148/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 100ms/step - loss: 2.5418e-05 - val_loss: 7.8267e-06
Epoch 149/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 99ms/step - loss: 2.5632e-05 - val_loss: 8.8896e-06
Epoch 150/150
102/102 ━━━━━━━━━━━━━━━━━━━━ 10s 96ms/step - loss: 2.6919e-05 - val_loss: 1.2128e-05

In [30]:
result = model.evaluate(X_test, y_test)
y_pred = model.predict(X_test)

42/42 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - loss: 0.0021
42/42 ━━━━━━━━━━━━━━━━━━━━ 2s 32ms/step

In [31]:
MAPE = mean_absolute_percentage_error(y_test, y_pred)
Accuracy = 1 - MAPE

In [32]:
print("Test Loss:", result)
print("Test MAPE:", MAPE)
print("Test Accuracy:", Accuracy)

Test Loss: 0.0020519602112472057
Test MAPE: 0.03988884797277014
Test Accuracy: 0.9601111520272299